Help 9742
wizaplace/wizaplace-php-sdk pull request #541
Opened 2022-07-18 13:15 UTC by theocoll342

## Checklist

- [ ] Changelog updated

2022-07-19 10:02 UTC, Nicolas-Masson-Wizaplace commented on CHANGELOG.md
> +- Added `\Wizaplace\SDK\Catalog\Product::getRelatedOffers`
```suggestion
- Added `\Wizaplace\SDK\Catalog\Product::getRelatedOffers`

```

2022-07-19 10:03 UTC, Guillaume-Rossignol commented on src/Pim/Product/RelatedProduct/RelatedProduct.php
> +    private $images;
On est sur que ce sont bien des Image[] ? J'imagine que les données dans le tableau donné à dénormalize sont plutôt brute

2022-07-21 06:54 UTC, Guillaume-Rossignol approved these changes

2022-07-21 09:05 UTC, Nicolas-Masson-Wizaplace commented on src/Catalog/RelatedProduct.php
> +        }
ici

2022-07-21 09:05 UTC, Nicolas-Masson-Wizaplace commented on src/Pim/Product/RelatedProduct/RelatedProduct.php
> +        $this->images = $data['images'];
@theocoll342 on a pas le même souci que ce que tu as corriger ici https://github.com/wizaplace/wizaplace-php-sdk/pull/541/files#r926438738 ?

2022-07-21 09:06 UTC, Nicolas-Masson-Wizaplace commented on src/Pim/Product/RelatedProduct/RelatedProduct.php
> +    public function getImages(): array
```suggestion
    /** @return Image[] */
    public function getImages(): array
```

2022-07-21 09:07 UTC, Nicolas-Masson-Wizaplace commented on src/Pim/Product/RelatedProduct/RelatedProduct.php
> +use Nette\Utils\Image;
hum je pense que c'est pas le bon import.

2022-07-21 09:10 UTC, Nicolas-Masson-Wizaplace requested changes
Quelques modifs et vérif supplémentaire à faire.

2022-07-25 15:14 UTC, Nicolas-Masson-Wizaplace approved these changes

2022-07-25 15:15 UTC, merged